const CFG=window.APP_CONFIG||{};const configured=CFG.SUPABASE_URL&&CFG.SUPABASE_ANON_KEY&&!CFG.SUPABASE_URL.includes('YOUR_');const db=configured?supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_ANON_KEY):null;
const stageNames=['상','주·춘추전국','진','한','남북조','수','당','문화권'];
const itemData={oracle:['🪨','갑골문'],bronze:['🏺','청동기'],iron:['⛏️','철기'],qin:['🏯','군현제'],han:['🧵','한 무제'],fusion:['🧱','호한 융합'],canal:['🚤','대운하'],changan:['🎫','장안 통행증'],culture:['📜','문화권 핵심']};
const Q=[
{stage:'상',item:'oracle',q:'중원 지역에서 기원전 1600년경 성립한 상(商)과 가장 관련 깊은 문자 자료는?',o:['갑골문','가나 문자','훈민정음','몽골 문자'],a:0,e:'상에서는 갑골문이 사용되었다. 은허에서 갑골문이 발견되어 당시 사회를 이해하는 중요한 자료가 된다.'},
{stage:'상',item:'bronze',q:'상 왕조의 청동기 문화에 대한 설명으로 가장 적절한 것은?',o:['청동으로 무기와 제사용 도구를 만들었다.','철제 농기구가 전국에 보급되었다.','대운하를 이용해 남북을 연결하였다.','불교 사원을 국가적으로 세웠다.'],a:0,e:'상은 청동기 문화를 발전시켰으며 청동으로 무기와 솥 등의 제사용 도구를 만들었다.'},
{stage:'주·춘추전국',item:'iron',q:'기원전 8세기경 춘추 전국 시대가 시작된 배경으로 가장 적절한 것은?',o:['주 왕실의 권위가 약해지고 제후국 간 경쟁이 벌어졌다.','수 왕조가 고구려 원정에 실패하였다.','한 무제가 흉노를 북쪽으로 몰아냈다.','북위가 화북 지역을 통일하였다.'],a:0,e:'주 왕실의 권위가 약해지면서 여러 제후국이 경쟁하여 춘추 전국 시대가 전개되었다.'},
{stage:'주·춘추전국',item:'iron',q:'춘추 전국 시대에 철기의 본격적인 사용이 가져온 변화는?',o:['농업 생산력이 증가하고 사회 구조가 변화하였다.','농업 생산력이 감소하고 도시가 해체되었다.','당이 멸망하고 중국이 분열되었다.','남북조의 대립이 바로 끝났다.'],a:0,e:'철기의 본격적 사용은 농업 생산력 증가와 사회 구조 변화를 촉진하였다.'},
{stage:'진',item:'qin',q:'진 시황제의 통일 정책에 해당하지 않는 것은?',o:['유교를 통치 이념으로 채택하였다.','문자·화폐·도량형을 통일하였다.','전국적으로 군현제를 실시하였다.','법가 이외의 사상을 탄압하였다.'],a:0,e:'유교를 통치 이념으로 채택한 것은 한 무제 때이다. 진 시황제는 문자·화폐·도량형 통일과 전국적 군현제 등을 추진하였다.'},
{stage:'진',item:'qin',q:'진이 오래 지속되지 못한 배경으로 가장 적절한 것은?',o:['가혹한 통치와 무리한 토목 공사로 백성의 반발을 샀다.','장안에서 외국 상인을 모두 추방하였다.','한화 정책 때문에 북방 민족이 반란을 일으켰다.','유교 관학화 때문에 제후국이 독립하였다.'],a:0,e:'진은 가혹한 통치와 만리장성 축조 등 무리한 토목 공사로 반발을 샀고 시황제 사후 농민 반란이 일어나 멸망하였다.'},
{stage:'한',item:'han',q:'기원전 202년 중원을 다시 통일한 왕조는?',o:['한','수','북위','당'],a:0,e:'한 고조가 기원전 202년 중원을 다시 통일하였다.'},
{stage:'한',item:'han',q:'한 무제의 활동으로 옳은 것은?',o:['영토를 확장하고 유교를 통치 이념으로 채택하였다.','한화 정책을 추진해 호한 융합을 주도하였다.','대운하를 건설하고 고구려를 여러 차례 공격하였다.','헤이조쿄를 건설하여 일본의 수도로 삼았다.'],a:0,e:'한 무제는 영토를 확대하고 중앙 집권 체제를 강화하였으며 유교를 통치 이념으로 채택하였다.'},
{stage:'한',item:'han',q:'한 무제의 대외 활동에 포함되는 것은?',o:['흉노를 북쪽으로 몰아내고 남월과 고조선을 멸망시켰다.','백제와 고구려를 멸망시키고 신라를 통일하였다.','몽골을 통일하고 유라시아 제국을 건설하였다.','왜의 여러 나라를 직접 군현으로 편입하였다.'],a:0,e:'한 무제는 흉노를 북쪽으로 몰아내고 남월과 고조선을 멸망시키는 등 적극적으로 세력을 확대하였다.'},
{stage:'남북조',item:'fusion',q:'5세기 전반 화북 지역을 통일한 북방 민족 왕조는?',o:['북위','동진','수','한'],a:0,e:'선비족이 세운 북위가 5세기 전반 화북 지역을 통일하였다.'},
{stage:'남북조',item:'fusion',q:'북위 효문제의 한화 정책이 가져온 변화로 가장 적절한 것은?',o:['북방 민족 문화와 한족 문화의 융합이 촉진되었다.','문자·화폐·도량형이 중국에서 처음 통일되었다.','주 왕실의 권위가 회복되었다.','중국과 서역의 교류가 완전히 중단되었다.'],a:0,e:'북위 효문제는 적극적인 한화 정책을 추진하였고 북방 민족과 한족 문화의 융합이 촉진되었다.'},
{stage:'수',item:'canal',q:'남북조의 오랜 분열을 끝내고 589년에 중국을 다시 통일한 왕조는?',o:['수','진(秦)','한','상'],a:0,e:'수는 589년에 남북조의 분열을 끝내고 중국을 다시 통일하였다.'},
{stage:'수',item:'canal',q:'수 양제와 가장 관련 깊은 사업은?',o:['남북을 연결하는 대운하 건설','갑골문 제작','북위의 한화 정책','주 왕실 중심의 제후국 경쟁'],a:0,e:'수 양제는 남북 지역을 연결하는 대운하를 건설하였다.'},
{stage:'당',item:'changan',q:'당의 수도 장안이 동아시아 교류사에서 중요한 이유로 가장 적절한 것은?',o:['여러 지역의 사신·상인·승려·유학생 등이 오가는 국제적인 도시였기 때문이다.','외국인의 출입을 금지한 폐쇄적인 군사 도시였기 때문이다.','춘추 전국 시대 제후국의 정치 연맹 도시였기 때문이다.','북위 효문제가 한화 정책을 처음 실시한 도시였기 때문이다.'],a:0,e:'당의 장안은 여러 지역에서 온 사신·상인·승려·유학생 등이 활동하는 국제적인 도시로 발전하였다.'},
{stage:'문화권',item:'culture',q:'당을 중심으로 한 교류 속에서 동아시아 여러 지역이 공유하게 된 문화 요소의 조합으로 옳은 것은?',o:['한자·율령·유교·불교','갑골문·가나·이슬람교·봉건제','라틴어·크리스트교·로마법·길드','몽골 문자·이슬람법·힌두교·카스트'],a:0,e:'당을 중심으로 교류가 활발해지는 과정에서 한자·율령·유교·불교 등이 동아시아 문화권의 공통 요소가 되었다.'}
];
let S={id:'',name:'',i:0,score:0,answered:false,items:new Set(),start:0,timer:null,practice:false};const $=x=>document.getElementById(x);const fmt=ms=>{let t=Math.max(0,Math.floor(ms/1000)),m=Math.floor(t/60),s=t%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`};
function screen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');scrollTo({top:0,behavior:'smooth'})}
function inventory(target='inventoryGrid'){let a=[...S.items];$(target).innerHTML=a.length?a.map(k=>`<div class="item"><div class="ico">${itemData[k][0]}</div><div>${itemData[k][1]}</div></div>`).join(''):'<div class="item"><div class="ico">□</div><div>비어 있음</div></div>'}
function stages(){let cur=Q[Math.min(S.i,Q.length-1)].stage,ci=stageNames.indexOf(cur);$('stageStrip').innerHTML=stageNames.map((x,i)=>`<span class="stage-pill ${i<ci?'done':i===ci?'current':''}">${x}</span>`).join('')}
function tick(){clearInterval(S.timer);let f=()=>$('timerLabel').textContent=fmt(Date.now()-S.start);f();S.timer=setInterval(f,500)}
function render(){let q=Q[S.i];S.answered=false;$('playerLabel').textContent=`${S.id} ${S.name}`;$('scoreLabel').textContent=`${S.score} / ${Q.length}`;$('progress').style.width=`${S.i/Q.length*100}%`;$('stageLabel').textContent=`STAGE · ${q.stage}`;$('qCount').textContent=`${S.i+1} / ${Q.length}`;$('qText').textContent=q.q;$('feedback').className='feedback hidden';$('nextBtn').classList.add('hidden');let order=[0,1,2,3].sort(()=>Math.random()-.5);$('options').innerHTML=order.map(i=>`<button class="option" data-i="${i}">${q.o[i]}</button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(+b.dataset.i,b));stages();inventory()}
function answer(i,b){if(S.answered)return;S.answered=true;let q=Q[S.i],ok=i===q.a;if(ok){S.score++;S.items.add(q.item);b.classList.add('correct')}else{b.classList.add('wrong');document.querySelectorAll('.option').forEach(x=>{if(+x.dataset.i===q.a)x.classList.add('correct')})}document.querySelectorAll('.option').forEach(x=>x.disabled=true);$('scoreLabel').textContent=`${S.score} / ${Q.length}`;let f=$('feedback');f.className=`feedback ${ok?'ok':'no'}`;f.innerHTML=`<b>${ok?'아이템 획득!':'오답 블록 제거!'}</b><br>${q.e}`;$('nextBtn').textContent=S.i===Q.length-1?'월드 클리어':'다음 지역으로';$('nextBtn').classList.remove('hidden');inventory()}
async function start(){let id=$('studentId').value.trim(),name=$('studentName').value.trim();if(!/^\d{3,10}$/.test(id)){return $('startMsg').textContent='학번을 숫자 3~10자리로 입력해 주세요.'}if(name.length<2){return $('startMsg').textContent='이름을 2글자 이상 입력해 주세요.'}$('startMsg').textContent='';S.id=id;S.name=name;S.practice=false;$('startBtn').disabled=true;if(configured){let {data,error}=await db.rpc('start_attempt',{p_student_id:id,p_student_name:name});if(error){$('startMsg').textContent='기록 서버 연결에 실패했습니다. 선생님께 알려 주세요.';$('startBtn').disabled=false;return}let r=data?.[0];if(r?.already_completed){let rr=await db.rpc('get_rank',{p_student_id:id});S.score=r.score||0;S.items=new Set(Object.keys(itemData));showResult(rr.data?.[0]||{});$('startBtn').disabled=false;return}}S.i=0;S.score=0;S.items=new Set();S.start=Date.now();screen('gameScreen');tick();render();$('startBtn').disabled=false}
async function finish(){clearInterval(S.timer);let r={duration_ms:Date.now()-S.start};if(!S.practice&&configured){let {data}=await db.rpc('finish_attempt',{p_student_id:S.id,p_score:S.score,p_total_questions:Q.length});if(data?.[0])r=data[0]}showResult(r)}
function showResult(r){$('resultPlayer').textContent=`${S.id} ${S.name}`;$('rankValue').textContent=S.practice?'연습':r.rank?`${r.rank}위`:'기록 미연결';$('rankTotal').textContent=S.practice?'공식 순위 미반영':r.total_completed?`완료 ${r.total_completed}명`:'Supabase 설정 필요';$('resultScore').textContent=`${S.score} / ${Q.length}`;$('resultAccuracy').textContent=`${Math.round(S.score/Q.length*100)}%`;$('resultTime').textContent=fmt(Number(r.duration_ms||Date.now()-S.start));inventory('resultInventory');screen('resultScreen')}
$('startBtn').onclick=start;$('nextBtn').onclick=()=>{if(!S.answered)return;if(S.i<Q.length-1){S.i++;render()}else finish()};$('practiceBtn').onclick=()=>{S.practice=true;S.i=0;S.score=0;S.items=new Set();S.start=Date.now();screen('gameScreen');tick();render()};$('serverBadge').textContent=configured?'실시간 순위 ON':'설정 필요 · 데모 모드';$('serverBadge').style.background=configured?'#294529':'#7a4936';